#!/usr/bin/env python3
"""
API endpoint for the Climate Economy Ecosystem Agent Router

This module provides the API endpoint for routing user queries to the appropriate
specialized agent based on user profile and query content.
"""

import os
import json
import uuid
from datetime import datetime
from typing import Dict, Any, Optional

from fastapi import APIRouter, Depends, HTTPException, Request, Response, status
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

# Import the agent router
from lib.agents.agent_router import agent_router, AgentType

# Import services
from lib.memory.memory_service import MemoryService, MemoryServiceError
from lib.redis.redis_service import RedisService, RedisServiceError
from lib.tracing.langsmith_service import TracingService, TracingServiceError

# Initialize services
memory_service = MemoryService()
redis_service = RedisService()
tracing_service = TracingService()

# Create router
router = APIRouter()

# Request models
class ChatRequest(BaseModel):
    """Chat request model"""
    user_id: str = Field(..., description="User ID")
    query: str = Field(..., description="User query")
    session_id: Optional[str] = Field(None, description="Session ID (optional)")
    agent_type: Optional[str] = Field(None, description="Force specific agent type (optional)")

# Response models
class ChatResponse(BaseModel):
    """Chat response model"""
    response: str = Field(..., description="Agent response")
    agent_type: str = Field(..., description="Agent type used")
    agent_name: str = Field(..., description="Agent name")
    session_id: str = Field(..., description="Session ID")
    interaction_id: str = Field(..., description="Interaction ID")
    timestamp: str = Field(..., description="Timestamp")

@router.post("/api/climate-chat/agent", response_model=ChatResponse)
async def chat_with_agent(request: ChatRequest) -> JSONResponse:
    """
    Chat with the appropriate specialized agent.
    
    Args:
        request: The chat request
        
    Returns:
        JSON response with the agent's response
    """
    # Create a run ID for tracing
    run_id = tracing_service.create_run_id()
    
    try:
        # Create a trace for the API call
        with tracing_service.trace(
            name="chat_with_agent_api",
            run_id=run_id,
            inputs=request.dict()
        ) as trace:
            # Generate session ID if not provided
            session_id = request.session_id or str(uuid.uuid4())
            
            # Generate interaction ID
            interaction_id = str(uuid.uuid4())
            
            # Check if we should force a specific agent type
            if request.agent_type:
                if request.agent_type not in [AgentType.PENDO, AgentType.JASMINE, AgentType.MARCUS, AgentType.MIGUEL]:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail=f"Invalid agent_type: {request.agent_type}"
                    )
                
                # Get the agent prompt
                prompt = await agent_router.get_agent_prompt(request.agent_type, request.user_id, request.query)
                
                # TODO: Call the LLM with the prompt to get a response
                # This is a placeholder - replace with actual LLM call
                agent_name = agent_router.agent_names.get(request.agent_type, "Assistant")
                response = f"This is a placeholder response from {agent_name}. In a real implementation, this would be generated by an LLM using the prompt."
                
                # Track the interaction
                await agent_router.track_agent_interaction(
                    request.user_id, 
                    request.agent_type, 
                    request.query, 
                    response, 
                    session_id
                )
                
                agent_type = request.agent_type
                agent_name = agent_router.agent_names.get(agent_type, "Assistant")
            else:
                # Process the query through the agent router
                agent_type, agent_name, response = await agent_router.process_query(
                    request.user_id,
                    request.query,
                    session_id
                )
            
            # Create the response
            chat_response = ChatResponse(
                response=response,
                agent_type=agent_type,
                agent_name=agent_name,
                session_id=session_id,
                interaction_id=interaction_id,
                timestamp=datetime.now().isoformat()
            )
            
            trace.end(outputs={
                "agent_type": agent_type,
                "agent_name": agent_name,
                "response_length": len(response)
            })
            
            return JSONResponse(
                status_code=status.HTTP_200_OK,
                content=chat_response.dict()
            )
            
    except MemoryServiceError as e:
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={"error": f"Memory service error: {str(e)}"}
        )
    except RedisServiceError as e:
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={"error": f"Redis service error: {str(e)}"}
        )
    except TracingServiceError as e:
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={"error": f"Tracing service error: {str(e)}"}
        )
    except Exception as e:
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={"error": f"Unexpected error: {str(e)}"}
        )

@router.get("/api/climate-chat/agents", response_model=Dict[str, str])
async def list_agents() -> JSONResponse:
    """
    List all available agents.
    
    Returns:
        JSON response with the list of agents
    """
    try:
        return JSONResponse(
            status_code=status.HTTP_200_OK,
            content=agent_router.agent_names
        )
    except Exception as e:
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={"error": f"Unexpected error: {str(e)}"}
        )
